services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:23.0.2
    network_mode: host
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: keycloak
    command: start-dev --http-port 18080 --import-realm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../keycloak-sms-authenticator/target/keycloak-sms-authenticator.jar:/opt/keycloak/providers/sms-auth.jar
      - ./keycloak-theme:/opt/keycloak/themes/wolpertinger
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
